### PR TITLE
Fix: Prevent Empty Prompt Responses in Chat View

### PR DESCRIPTION
**Pull request by superiorsd10**
### Fixes Issue #141 

---

### Description

The issue arises in the chat view of the FlutterGPT extension when the user enters empty text and presses Enter. Instead of responding, the extension should prompt the user to enter a meaningful question or input.

### Implementation

- **Added Snackbar Div:** Introduced a new `snackbar` ID div in [chat.html](https://github.com/superiorsd10/fluttergpt/blob/empty-text-chat-view-bug/media/chat/chat.html#L176) to facilitate displaying messages to the user.

- **Styled Snackbar:** Applied styles for the `snackbar` div, including a `fadeInOut` animation for a smoother user experience.

- **Empty Prompt Check:** Modified [main.js](https://github.com/superiorsd10/fluttergpt/blob/empty-text-chat-view-bug/media/chat/scripts/main.js#L157) to check for an empty prompt value before processing the user's input.

- **Snackbar Display Logic:** Implemented logic in [main.js](https://github.com/superiorsd10/fluttergpt/blob/empty-text-chat-view-bug/media/chat/scripts/main.js#L157) to display the `snackbar` when an empty prompt is detected.

- **Snackbar Function:** Added a function in [main.js](https://github.com/superiorsd10/fluttergpt/blob/empty-text-chat-view-bug/media/chat/scripts/main.js#L175) specifically for displaying the `snackbar` with a fade-in and fade-out effect.

- **Delay Function:** Introduced a delay function in [main.js](https://github.com/superiorsd10/fluttergpt/blob/empty-text-chat-view-bug/media/chat/scripts/main.js#L170) to handle asynchronous timing for showing and hiding the `snackbar`.

---

### Screen Recording

https://github.com/Welltested-AI/fluttergpt/assets/92971894/62b369fa-4d5d-4900-a02b-dec0e1081a40

---

### Additional Notes

- The choice of orange color for the snackbar background was made to ensure visibility and grab the user's attention without being too intrusive. Orange is often associated with warning or attention-grabbing elements in user interfaces, making it suitable for notifying users about important messages.
- Please tap on file links in this PR to navigate directly to the exact line of code implemented.

### CODE REVIEW

**Comment by yatendra2001** [comment]
hey @superiorsd10 , this looks really good. We need a few changes:

1. Keep warning message simple such as "No input text found."
2. Also better if we can show a simple warning icon just for aesthetics.
3. Also can we go with some simple color for background such as ffcc00, this looks too hard on eye.

**Comment by superiorsd10** [comment]
> hey @superiorsd10 , this looks really good. We need a few changes:
> 
> 1. Keep warning message simple such as "No input text found".
> 2. Also better if we can show a simple warning icon just for aesthetics.
> 3. Also can we go with some simple color for background such as ffcc00, this looks too hard on eye.

I have made the suggested changes in my recent commit. Please review it. Thank you :)

### Changes Made
- Added the `font-awesome` CDN in the `head` in [chat.html](https://github.com/superiorsd10/fluttergpt/blob/empty-text-chat-view-bug/media/chat/chat.html#L8).
- Added the `warning-icon` in the snackbar in [chat.html](https://github.com/superiorsd10/fluttergpt/blob/empty-text-chat-view-bug/media/chat/chat.html#L184).
- Changed the warning text to `No input text found`.
- Changed the background color of the snackbar to `#ffcc00`.

### Screen Recording

https://github.com/Welltested-AI/fluttergpt/assets/92971894/5a3a6833-52c5-458d-9b5d-c82ee794a50b

**Comment by samyakkkk** [comment]
@superiorsd10 thanks for your prompt and detailed submissions. 

**This is an optional request if you can squeeze it in:**

Instead of snackbar, could we have a toast like rectangle error indicator slide up right over the text field. It will be much cleaner UX. we can also use it to show other errors related to failed requests and so.

Screenshot 2023-12-29 at 8 46 44 PM

thanks :)

**Comment by superiorsd10** [comment]
> @superiorsd10 thanks for your prompt and detailed submissions.
> 
> **This is an optional request if you can squeeze it in:**
> 
> Instead of snackbar, could we have a toast like rectangle error indicator slide up right over the text field. It will be much cleaner UX. we can also use it to show other errors related to failed requests and so.
> 
> Screenshot 2023-12-29 at 8 46 44 PM
> thanks :)

Sure, that too is a great idea! I'll be working on it :)

**Comment by superiorsd10** [comment]
Hello @samyakkkk 👋

Please review the attached screen recording for the updated toast. If you have any feedback or if there are no further adjustments needed, I'll proceed with making a pull request. Your input is highly appreciated!

https://github.com/Welltested-AI/fluttergpt/assets/92971894/f80e521e-d6a4-42fc-8e57-1a9945f9e229

**Comment by samyakkkk** [comment]
Good work @superiorsd10! I was actually suggesting something slightly different but no worries, we can come back to it later. 

It is important to merge this ticket for now so our users don't face the empty text issue. 

Can you please solve the merge conflicts? I'll merge.

**Comment by superiorsd10** [comment]
> Good work @superiorsd10! I was actually suggesting something slightly different but no worries, we can come back to it later.
> 
> It is important to merge this ticket for now so our users don't face the empty text issue.
> 
> Can you please solve the merge conflicts? I'll merge.

Thank you @samyakkkk :)

I have committed the changes to display toast and also resolved the merge conflicts.

**Comment by samyakkkk** [comment]
@yatendra2001 let's test it and merge if all looks good.

**Review by yatendra2001 — APPROVED** [review]
Hey @superiorsd10 awesome PR. 1 suggestion, don't comment for stuff that seems obvious from the code.

For example, comments on line 178, 181 and 184 aren't required since they looks quite obvious from the code.

Screenshot 2024-01-02 at 6 35 23 PM

Merging the PR.

**Comment by yatendra2001** [comment]
awesome work!

**Comment by superiorsd10** [comment]
> Hey @superiorsd10 awesome PR. 1 suggestion, don't comment for stuff that seems obvious from the code.
> 
> For example, comments on line 178, 181 and 184 aren't required since they looks quite obvious from the code.
> 
> Screenshot 2024-01-02 at 6 38 07 PM
> Merging the PR.

Hello @yatendra2001 👋

Thank you for your positive feedback and suggestion! I'll definitely keep your advice in mind and refrain from commenting on obvious aspects in the future. 

Thanks again,

**Pull request merged**
