### PR TITLE
feat: added update manager

### PR DESCRIPTION
**Pull request by khurramrizvi**
## Description

This PR implements update feature request as raised in #126 

### Implementation Details
- Added `UpdateManager` class to manage extension updates.
- **checkUpdate** method is called on extension **activation** to check for latest update.
- A notification is shown to user, if current local extension version is older than latest update available.

### Technical Details
The latest version is obtained from the `metadata` received from extension's marketplace.
The version is then compared with the local copy of extension.
A notification is shown if latest live version is greater than current local version of extension.

### Motivation for Approach
The approach eliminates the need of maintaining any version configuration variable on server.
No additional steps are required after publishing latest release of extension.

### CODE REVIEW

**Comment by yatendra2001** [comment]
hey @khurramrizvi , can you switch to previous version of flutterGPT and attach a screen recording of how it works in real time?

**Comment by khurramrizvi** [comment]
Attaching GIF Demonstrating update feature.

Hope this works  :)

fluttergpt_update_demo

**Comment by yatendra2001** [comment]
@khurramrizvi a quick questions, does it only show a notification once the user opens flutterGPT??

**Comment by khurramrizvi** [comment]
@yatendra2001 Yes, it shows a notification with a button to redirect to the marketplace to download the latest version.

**Comment by khurramrizvi** [comment]
@yatendra2001 Could you please review this PR once.

**Comment by yatendra2001** [comment]
hey @khurramrizvi , we're not keeping update manager for a release as of now. Since a notification everytime user taps on fluttergpt won't be a good UX. I'm going to close this PR for now. Let's work on it at later stage when it's required.

**Comment by yatendra2001** [comment]
@samyakkkk yeah sure, it does make sense to include it since we're actively releasing nowadays. 
Works awesome, thanks for contributing @khurramrizvi . Merging it.

**Comment by khurramrizvi** [comment]
@yatendra2001Glad, it was merged 😄

**Pull request merged**
